model1:
  _target_: sklearn.ensemble.RandomForestClassifier
  n_estimators: 100


model2: 
  _target_: sklearn.ensemble.RandomForestClassifier
  _args_: [300]


model3:
  _target_: sklearn.ensemble.RandomForestClassifier
  _partial_: True